- repo: local
  hooks:
    - id: flutter-format
      name: format
      entry: dart format -l 150 .
      language: system
      files: lib/* # Only format source files
      exclude: lib/src/utils.dart # Exclude utils