name: Dart CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_web:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get

      - name: Change version
        run: sh _bump.sh $GITHUB_REF $GITHUB_RUN_NUMBER

      - name: Build web release
        run: flutter build web --release

      - name: Use random for fix cache
        run: |
          ran=$RANDOM
          echo $ran
          mv -i build/web/main.dart.js build/web/main.$ran.dart.js
          sed -i '' 's|main\.dart\.js\?v\=[0-9]*|main\.'$ran'\.dart\.js|g' ./build/web/index.html ./build/web/flutter_service_worker.js
          sed -i '' 's|main\.dart\.js|main\.'$ran'\.dart\.js|g' ./build/web/index.html ./build/web/flutter_service_worker.js

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: build/web
          fqdn: doppio.dev
        env:
          GITHUB_TOKEN: ${{ secrets.ci_token }}

  build_mac_os:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Change version
        run: sh _bump.sh $GITHUB_REF $GITHUB_RUN_NUMBER

      # - name: Install create-dmg
      #   run: brew install create-dmg

      - name: Build macos release
        run: flutter build macos --release

      - name: Build dmg
        run: sh _dmg.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: release/macos/

  distribute:
    needs: [build_mac_os]
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-dmg
          path: release/macos/

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Get application version
        id: app_ver
        run: echo "app_ver=$(flutter pub run doppio_utils_config:get_ver)+($GITHUB_RUN_NUMBER)" >> $GITHUB_OUTPUT
      
      # https://github.com/ahdbilal/firstiosapp/blob/master/.github/workflows/build_distribute.yml
      - name: Read Configuration
        id: dist_config
        run: |
          release_type=$(flutter pub run doppio_utils_config:get_config_distr path=.distribute/config.yml branch=master propertyName=release_type)
          draft=$(flutter pub run doppio_utils_config:get_config_distr path=.distribute/config.yml branch=master propertyName=draft)
          prerelease=$(flutter pub run doppio_utils_config:get_config_distr path=.distribute/config.yml branch=master propertyName=prerelease)
          echo "release_type=${release_type//\'}" >> $GITHUB_OUTPUT
          echo "draft=${draft//\'}" >> $GITHUB_OUTPUT
          echo "prerelease=${prerelease//\'}" >> $GITHUB_OUTPUT

      - name: Create a Release
        id: create-release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ci_token }}
        with:
          tag_name: v_${{ steps.app_ver.outputs.app_ver  }}_${{ steps.dist_config.outputs.release_type }}
          name: ${{ steps.dist_config.outputs.release_type }} v_${{ steps.app_ver.outputs.app_ver  }}
          body: ${{ env.COMMIT_MESSAGE }}
          draft: ${{ steps.dist_config.outputs.draft }}
          prerelease: ${{ steps.dist_config.outputs.prerelease }}
          files: macos/build.zip

      - name: Zip Build
        run: zip -rj macos/build.zip release/macos/
