name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:latest

    steps:
    - uses: actions/checkout@v1
    - name: Export PATH
      run: export PATH="$PATH:/home/cirrus/sdks/flutter/bin"
    - name: Running flutter doctor
      run: flutter doctor
    - name: Install dependencies
      run: flutter pub get
    - name: Build web release
      run: flutter build web --release
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.1
      with:
        build_dir: build/web
