name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Running flutter doctor
      run: flutter doctor
    - name: Enable web
      run: flutter config --enable-web
    - name: Install dependencies
      run: flutter pub get
    - name: Change version
      run: sh _bump.sh $GITHUB_REF $GITHUB_RUN_ID
    - name: Build web release
      run: flutter build web --release
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.1
      with:
        build_dir: build/web
      env:
        GITHUB_TOKEN: ${{ secrets.ci_token }}
